import {
  addClicked,
  closeClicked,
  copyClicked,
  deleteClicked,
  editClicked,
  editCloseClicked,
  forwardClicked,
  onInputChange,
  onKeyPress,
  onChatMenuClick,
  searchInputState,
  onPersonMenuClick,
  onCloseModalClick,
  onForwardChat,
  onLoadComplete,
  personClicked,
  saveClicked,
} from "../StateManager/actionCreator";

export const actionImports = {
  addClicked,
  closeClicked,
  copyClicked,
  deleteClicked,
  editClicked,
  editCloseClicked,
  forwardClicked,
  onInputChange,
  onKeyPress,
  onChatMenuClick,
  searchInputState,
  onPersonMenuClick,
  onCloseModalClick,
  onForwardChat,
  onLoadComplete,
  personClicked,
  saveClicked,
};
